-- 家教中介管理系统：初始Schema（V1）
-- 仅两张业务表：orders（家长需求订单）、applications（老师报名）。
-- 金额一律整数分；时间戳一律UTC ISO文本；SQLite内部表（如sqlite_sequence）不视为业务表。

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_no TEXT NOT NULL UNIQUE,
  parent_name TEXT NOT NULL,
  parent_wechat TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  child_grade TEXT NOT NULL,
  subjects TEXT NOT NULL,
  learning_situation TEXT NOT NULL,
  tutoring_goal TEXT NOT NULL,
  teaching_mode TEXT NOT NULL CHECK (teaching_mode IN ('online','offline')),
  location_detail TEXT NOT NULL,
  public_area TEXT NOT NULL,
  weekly_schedule TEXT NOT NULL,
  public_schedule TEXT NOT NULL,
  sessions_per_week INTEGER NOT NULL CHECK (sessions_per_week > 0),
  session_minutes INTEGER NOT NULL CHECK (session_minutes > 0),
  expected_start_date TEXT,
  hourly_pay_cents INTEGER NOT NULL CHECK (hourly_pay_cents > 0),
  pay_negotiable INTEGER NOT NULL CHECK (pay_negotiable IN (0,1)),
  gender_preference TEXT NOT NULL CHECK (gender_preference IN ('any','male','female')),
  teacher_requirements TEXT NOT NULL DEFAULT '',
  public_requirements TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('recruiting','reviewing','awaiting_trial','trialing','completed','paused','cancelled')),
  paused_from_status TEXT CHECK (paused_from_status IS NULL OR paused_from_status IN ('recruiting','reviewing')),
  current_application_id INTEGER REFERENCES applications(id),
  matched_application_id INTEGER REFERENCES applications(id),
  completed_at TEXT,
  cancelled_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  source_template_text TEXT,
  creation_request_id TEXT UNIQUE
);

CREATE TABLE applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  application_no TEXT NOT NULL UNIQUE,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  teacher_name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('male','female')),
  wechat TEXT NOT NULL,
  phone TEXT NOT NULL,
  university TEXT NOT NULL,
  major TEXT NOT NULL,
  study_year TEXT NOT NULL,
  teachable_subjects_grades TEXT NOT NULL,
  achievements TEXT NOT NULL DEFAULT '',
  teaching_experience TEXT NOT NULL,
  strengths_and_plan TEXT NOT NULL,
  available_schedule TEXT NOT NULL,
  earliest_start_date TEXT,
  accepts_order_pay INTEGER NOT NULL CHECK (accepts_order_pay IN (0,1)),
  expected_hourly_pay_cents INTEGER CHECK (expected_hourly_pay_cents IS NULL OR expected_hourly_pay_cents > 0),
  can_attend_trial INTEGER NOT NULL CHECK (can_attend_trial IN (0,1)),
  trial_constraints TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  attachments_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL CHECK (status IN ('submitted','recommended','awaiting_trial','trial_passed','trial_failed','withdrawn','order_closed','direct_cooperation')),
  trial_at TEXT,
  cooperation_confirmed_at TEXT,
  agency_fee_cents INTEGER CHECK (agency_fee_cents IS NULL OR agency_fee_cents >= 0),
  deposit_due_cents INTEGER CHECK (deposit_due_cents IS NULL OR deposit_due_cents >= 0),
  deposit_received_cents INTEGER NOT NULL DEFAULT 0 CHECK (deposit_received_cents >= 0),
  deposit_received_at TEXT,
  deposit_refunded_cents INTEGER NOT NULL DEFAULT 0 CHECK (deposit_refunded_cents >= 0),
  deposit_refunded_at TEXT,
  fee_supplement_received_cents INTEGER NOT NULL DEFAULT 0 CHECK (fee_supplement_received_cents >= 0),
  fee_supplement_received_at TEXT,
  fee_supplement_refunded_cents INTEGER NOT NULL DEFAULT 0 CHECK (fee_supplement_refunded_cents >= 0),
  fee_supplement_refunded_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  source_template_text TEXT,
  creation_request_id TEXT UNIQUE,
  finance_operations_json TEXT NOT NULL DEFAULT '[]'
);

CREATE INDEX idx_applications_order_id ON applications(order_id);
CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_updated_at ON orders(updated_at);
